### ISSUE TITLE
[Question]: 如何美化 lint 错误提示？

### ISSUE THREAD

**Issue by y4n6** [miyuesc/bpmn-js-questions#10]
### 遇到了什么问题？

首先，感谢大佬无私的贡献，之前在群里也发红包表示了感谢。没有前人栽树，相信在国内选型bpmnjs做设计器的研发人员会少很多。

linting.active启用后，如何美化 lint 错误提示？
![c45eea0794bb42170d2c88c67a3bd4f](https://github.com/user-attachments/assets/e1c9e230-6c76-4c47-b0d4-67e100873ea9)

《Bpmn.js 进阶指南之Lint流程校验(四)自定义检验》末尾提到说明没有在专栏找到，跪谢大佬明示。
![0559632cedcfd2fded53aeafdbfe4e0](https://github.com/user-attachments/assets/df73e8e3-e38d-449c-bfb8-9288573170b5)

### bpmn-js 版本

17.0.2

### 技术栈基础库版本

Vue2.7.16

**Comment by miyuesc** [comment]
截图所示是收费版基于bpmnlint开发的检验组件，bpmn-js-bpmnlint是官方基于bpmnlint开发的bpmn-js的一个直接使用的插件，如果需要修改，可以自己重新写css样式，或者自行实现校验模块。

**Comment by y4n6** [comment]
明白，感谢大佬解答和分享 orz
我尝试自己实现校验模块，后来的兄弟如果需要demo也可以找我。
